theme: jekyll-theme-hacker

title: "ESP32, IoT & Home Automation Projects"
description: "A collection of ESP32 and IoT projects exploring smart home automation, sensors, security systems, dashboards, notifications, and integrations with cloud services."
url: "https://marchino1978.github.io"
baseurl: ""

google_site_verification: "281O-yML_ohanee0iyLxOd_9-EvMqOgNIDNAhmnlzu8"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
